### ISSUE TITLE
Evaluar la creación de formularios con web components para manejo de información básica

### ISSUE THREAD

**Issue by corio27** [udistrital/web-components#7]

**Comment by fabianLeon** [comment]
Se realiza capacitación sobre el uso del proyecto [web-components](https://github.com/udistrital/web-components) para construcción de webcomponents en angular 
[grabación](https://drive.google.com/file/d/1qpWRzyoaO9B47CRXR6Z1Omw8bpRg_vQi/view?usp=sharing)
