### ISSUE TITLE
Evaluar modulo de información básica del cliente sga

### ISSUE THREAD

**Issue by corio27** [udistrital/web-components#8]
- [x] Verificar funcionamiento del cliente
 - [x] Analizar estructura del componente de información básica
 - [x] Concertar reunión con proyecto de sistema de gestión académica
 - [x] Generar propuestas para manejo de formularios reactivos en Angular

**Comment by JocoolQ** [comment]
Se verifica funcionamiento del cliente "sga_cliente" y se analiza e identifica la estructura relacionada al formulario de información básica.

A continuación se muestra la estructura de archivos de los componentes asociados que se encuentran dentro de la ruta (src/app/pages/inscripcion):

![inscripcion component](https://user-images.githubusercontent.com/24370138/104641749-2c0c4d00-5678-11eb-8149-aaa9e4d7dc37.PNG)

**Comment by criss201x** [comment]
junto con @JocoolQ  y @fabianbarreto02 se realizo reunión para retroalimentar conceptos  de los formularios de terceros en el cliente SGA, [link de la grabación](https://drive.google.com/file/d/1HKWvba5LPdTT9nywyM_lt1gKF1gGns0T/view?usp=sharing)

**Comment by JocoolQ** [comment]
Se propone junto con @criss201x, @danzola y @fabianLeon el uso de [Angular Reactive Forms](https://angular.io/guide/reactive-forms) y [Angular Material](https://material.angular.io/) para la construcción de webcomponent asociado a formularios de registro de información básica de terceros.
